#!/usr/local/bin/expect -f
set timeout 1
set rl [lindex $argv 0]
spawn $env(SHELL)
expect "*$ "
send -- "source $rl"
expect -exact "source $rl"
send -- "\r"
expect "*terminators*"
send -- "type rl_reset\r"
expect {
    timeout { exit 1 }
    "*READLINE_LINE*"
    }
send -- ""
expect eof
