#!/usr/bin/expect -f

set timeout 1
set rl [lindex $argv 0]
spawn $env(SHELL)
expect "*$ "
send -- "source $rl"
expect -exact "source $rl"
send -- "\r"
expect "*terminators*"
send -- "type rl_reset\r"
expect {
    timeout { exit 1 }
    "*READLINE_LINE*"
    }

puts "bash tab completion"
puts ""
send -- "ls -lta ../readline\t\r"
expect {
    timeout { exit 1 }
    "*travis.yml*"
    }

puts "bash multiline 1"
puts ""
send -- "\r"
send -- "for i in test1 2; do\n"
send -- "echo \$i\$i\n"
send -- "done\n"
expect {
    timeout { exit 1 }
    "*test1test1*"
    }




send -- ""
expect eof
